spring:
  application:
    name: spring-cloud-eureka

server:
  port: 8761

logging:
  file: ./logs/EurkaApplication.log
  level.org.springframework.web: warn

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/